### ISSUE TITLE
Update config files to new gitbook approach

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/managing-innersource-projects#10]
Since first publishing this book on https://gitbook.com, they seem to have changed the way they do things.
e.g. some of the configuration options that were available back then are likely not available any more.

From a quick check we could likely remove these things:
```
book.json
/styles
```

**Comment by spier** [comment]
This was implemented in #47

**Comment by rrrutledge** [comment]
Thanks for cleaning this up, @spier ❗️

**Comment by spier** [comment]
Absolutely. "cleanup" is my middle name :)

**Comment by rrrutledge** [comment]
I always wondered 😉.  And I always imagined you as a “Paul”.
