### ISSUE TITLE
Automate creation of the GQM diagram

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/managing-innersource-projects#37]
- [x] Add a README.md
- [x] Merge PR, initial version
- [x] Add test coverage & test coverage reporting.
- [x] Add to github pipeline.
- [ ] Merge PR, final version

**Comment by jeffabailey** [comment]
1. A command is created that generates the graph of issue.
2. The command creates a mermaid diagram from the graph.

**Comment by spier** [comment]
Which diagram do you want to auto-generate?
And what should be used as input data for this generation?

**Comment by jeffabailey** [comment]
The mermaid diagram.
The markdown files.

Here's a first stab at a solution.

https://github.com/jeffabailey/gqm_gen

```npm i && npm run start```

It should generate:

```
```mermaid
graph LR
Goal1((Goal1))
Question1{Question2}
Metric1((Metric1))
Goal4((Goal4))
Goal1-->Question1
Goal1-->Metric1
Question1-.->Metric1
Metric1==>Goal1
```

It's not done, but sharing the code early.

Do we want to put this code somewhere in particular?

**Comment by rrrutledge** [comment]
Ideally in the repo somewhere - if we put it in something like a “scripts” folder will GitBook try to deploy it?

**Comment by spier** [comment]
gitbook will only include the files in the book that are listed in [SUMMARY.md](https://github.com/InnerSourceCommons/managing-innersource-projects/blob/main/SUMMARY.md
)

**Comment by spier** [comment]
I am still unclear what is being discussed here though.

Why do you want to generate the GQM diagram automatically?

**Comment by rrrutledge** [comment]
It is a philosophy - that in general mechanical, repetitive tasks should be automated to save time and errors.

**Comment by spier** [comment]
Yeah, I figured the bit about the philosophy.

Maybe the mission context is this:
Are you expecting to add a lot of Goals, Questions, and Metrics to that graph over time?

**Comment by rrrutledge** [comment]
Hope so!  We know that there are so many out there that people have talked about that aren’t added here.

https://miro.com/app/board/uXjVM3USbSE=/

**Comment by rrrutledge** [comment]
Thank you, @jeffabailey

**Comment by dellagustin-sap** [comment]
Closed automatically by the PR, but there are still open points.
