### ISSUE TITLE
Question on metrics

### ISSUE THREAD

**Issue by JustinGOSSES** [InnerSourceCommons/managing-innersource-projects#43]
If I have an alternative definition of a metric, meaning a different way to count it, how should that be handled? https://github.com/InnerSourceCommons/managing-inner-source-projects/blob/master/measuring/metrics/code-contributions.md

Options include Adding a second definition or making different metric or ?

**Comment by rrrutledge** [comment]
I am thinking different metric - maybe we can rename the first metric to something more specific so its scope does not include yours.

**Comment by spier** [comment]
@JustinGOSSES how would you count this metric?

If it is the same intention, just a different way to count, then I would keep it in the same metric file, and describe the alternative way to measure it.

If the goal of your metric is an entirely different one, then I would create a new metric.
