### ISSUE TITLE
Spelling of InnerSource as one word

### ISSUE THREAD

**Issue by spier** [InnerSourceCommons/managing-innersource-projects#49]
I suggest to change the spelling of InnerSource from two words to one word in these places:

- the name of the gitbook project. "Managing Inner Source Projects book" => "Managing InnerSource Projects book"
- this will automatically change the URL of the deployed gitbook too => `https://innersourcecommons.gitbook.io/managing-innersource-projects/` (redirects from old to new URL will work automatically)
- this GitHub repo: => `https://github.com/InnerSourceCommons/managing-innersource-projects` (redirects from old to new URL will work automatically)

If nothing speaks against this, I happy to go ahead and implement this.

**Comment by spier** [comment]
And yes, I know that this is nitpicking :)

However, if we want to drive the term "InnerSource", it does help a little bit if we use it in a consistent spelling.
That is my hope at least :)

**Comment by rrrutledge** [comment]
Sounds great - go ahead!

**Comment by spier** [comment]
- [x] Renamed the repo.
- [x] Renamed the gitbook. 
- [x] Reconfigure integration from github repo => gitbook 
- [x] Confirmed that the gitbook URL is updated (actually had to do this manually
- [x] Fixed link from the innersource website to this book
- [ ] Update link from repo to book

**Comment by spier** [comment]
✅ this is all done

@jeffabailey @rrrutledge you probably have to update the remote URL of this repo in your local clones.

Something similar to do should do that:
`git remote set-url origin git@github.com:InnerSourceCommons/managing-innersource-projects.git`

**Comment by rrrutledge** [comment]
Amazing!
