### ISSUE TITLE
Adding branch protection rules to master

### ISSUE THREAD

**Issue by yuhattor** [InnerSourceCommons/managing-innersource-projects#59]
I got confused with a different PR, merged the unreviewed branch into mainline, and rushed to revert.

The impact was still small now, but is it possible to apply a branch protection rule to master to prevent this from happening in the future?

Related PR: https://github.com/InnerSourceCommons/managing-innersource-projects/pull/22

**Comment by rrrutledge** [comment]
![image](https://github.com/InnerSourceCommons/managing-innersource-projects/assets/9609562/b47aaf74-81b5-45c5-975f-6ba6068fa0d8)

**Comment by yuhattor** [comment]
Thank you !
